Fixes and mild debugging

diff --git a/sync-brews b/sync-brews
--- a/sync-brews
+++ b/sync-brews
@@ -1,45 +1,48 @@
 #!/bin/bash
 
-# Sync Homebrew installations between Macs via Dropbox
+# Sync Homebrew installations between Macs via Dropbox, including casks
 #
 
 BREW="/usr/local/bin/brew"
+DROPBOX="$HOME/Dropbox (Personal)"
 
-# first get local settings
+# First get local settings
 echo "Reading local settings ..."
 rm -f /tmp/brew-sync.*
 $BREW tap > /tmp/brew-sync.taps
-$BREW list > /tmp/brew-sync.installed
+$BREW list -1 > /tmp/brew-sync.installed
 $BREW cask list -1 > /tmp/brew-sync.casks
 
-# then combine it with list in Dropbox
+# Then combine it with list in Dropbox
 echo "Reading settings from Dropbox ..."
-[ -e ~/Dropbox/Apps/Homebrew/brew-sync.taps ] && cat ~/Dropbox/Apps/Homebrew/brew-sync.taps >> /tmp/brew-sync.taps
-[ -e ~/Dropbox/Apps/Homebrew/brew-sync.installed ] && cat ~/Dropbox/Apps/Homebrew/brew-sync.installed >> /tmp/brew-sync.installed
-[ -e ~/Dropbox/Apps/Homebrew/brew-sync.casks ] && cat ~/Dropbox/Apps/Homebrew/brew-sync.casks >> /tmp/brew-sync.casks
+[ -e "$DROPBOX/Apps/Homebrew/brew-sync.taps" ] && cat "$DROPBOX/Apps/Homebrew/brew-sync.taps" >> /tmp/brew-sync.taps
+[ -e "$DROPBOX/Apps/Homebrew/brew-sync.installed" ] && cat "$DROPBOX/Apps/Homebrew/brew-sync.installed" >> /tmp/brew-sync.installed
+[ -e "$DROPBOX/Apps/Homebrew/brew-sync.casks" ] && cat "$DROPBOX/Apps/Homebrew/brew-sync.casks" >> /tmp/brew-sync.casks
 
-# make the lists unique and sync into Dropbox
 echo "Syncing to Dropbox ..."
-mkdir -p ~/Dropbox/Apps/Homebrew
-cat /tmp/brew-sync.taps | sort | uniq > ~/Dropbox/Apps/Homebrew/brew-sync.taps
-cat /tmp/brew-sync.installed | sort | uniq > ~/Dropbox/Apps/Homebrew/brew-sync.installed
-cat /tmp/brew-sync.casks | sort | uniq > ~/Dropbox/Apps/Homebrew/brew-sync.casks
+mkdir -p "$DROPBOX/Apps/Homebrew"
+cat /tmp/brew-sync.taps | sort | uniq > "$DROPBOX/Apps/Homebrew/brew-sync.taps"
+cat /tmp/brew-sync.installed | sort | uniq > "$DROPBOX/Apps/Homebrew/brew-sync.installed"
+cat /tmp/brew-sync.casks | sort | uniq > "$DROPBOX/Apps/Homebrew/brew-sync.casks"
 
-# Set taps
-echo "Enabling taps ..."
-for TAP in `cat ~/Dropbox/Apps/Homebrew/brew-sync.taps`; do
-	$BREW tap ${TAP} >/dev/null
+echo; echo "Enabling taps..."
+for TAP in `cat "$DROPBOX/Apps/Homebrew/brew-sync.taps"`; do
+ echo -n "."
+#  $BREW tap ${TAP} #>/dev/null
 done
 
-# Install missing Homebrew packages
-echo "Install missing packages ..."
-for PACKAGE in `cat ~/Dropbox/Apps/Homebrew/brew-sync.installed`; do
-	$BREW list ${PACKAGE} >/dev/null
-	[ "$?" != "0" ] && $BREW install ${PACKAGE}
+echo; echo "Install missing packages..."
+for PACKAGE in `cat "$DROPBOX/Apps/Homebrew/brew-sync.installed"`; do
+  echo -n "."
+#  $BREW list ${PACKAGE} #>/dev/null
+#  [ "$?" != "0" ] && $BREW install ${PACKAGE}
 done
 
-echo "Install missing casks ..."
-for CASK in `cat ~/Dropbox/Apps/Homebrew/brew-sync.casks`; do
-	$BREW cask list -1 ${CASK} >/dev/null
-	[ "$?" != "0" ] && $BREW cask install ${CASK}
+echo; echo "Install missing casks..."
+for CASK in `cat "$DROPBOX/Apps/Homebrew/brew-sync.casks"`; do
+  echo -n "."
+#  $BREW cask list -1 ${CASK} #>/dev/null
+#  [ "$?" != "0" ] && $BREW cask install ${CASK}
 done
+
+echo; echo "All done"
